🇺🇸:
  国旗: 🇺🇸
  英文: US
  中文: 美国
  其他:
    - United States
    - CT
    - UnitedStates
🇧🇷:
  国旗: 🇧🇷
  英文: BR
  中文: 巴西
  其他:
    - Brazil
🇨🇳:
  国旗: 🇨🇳
  英文: CN
  中文: 中国
  其他:
    - China
🇷🇺:
  国旗: 🇷🇺
  英文: RU
  中文: 俄罗斯
  其他:
    - Russian Federation
    - RussianFederation
🇮🇳:
  国旗: 🇮🇳
  英文: IN
  中文: 印度
  其他:
    - India
🇬🇧:
  国旗: 🇬🇧
  英文: GB
  中文: 英国
  其他:
    - United Kingdom
    - UK
    - UnitedKingdom
🇮🇩:
  国旗: 🇮🇩
  英文: ID
  中文: 印度尼西亚
  其他:
    - Indonesia
🇩🇪:
  国旗: 🇩🇪
  英文: DE
  中文: 德国
  其他:
    - Germany
🇦🇺:
  国旗: 🇦🇺
  英文: AU
  中文: 澳大利亚
  其他:
    - Australia
🇵🇱:
  国旗: 🇵🇱
  英文: PL
  中文: 波兰
  其他:
    - Poland
🇨🇦:
  国旗: 🇨🇦
  英文: CA
  中文: 加拿大
  其他:
    - Canada
🇺🇦:
  国旗: 🇺🇦
  英文: UA
  中文: 乌克兰
  其他:
    - Ukraine
🇫🇷:
  国旗: 🇫🇷
  英文: FR
  中文: 法国
  其他:
    - France
🇧🇩:
  国旗: 🇧🇩
  英文: BD
  中文: 孟加拉国
  其他:
    - Bangladesh
🇳🇱:
  国旗: 🇳🇱
  英文: NL
  中文: 荷兰
  其他:
    - Netherlands
    - AN
    - 安的列斯
    - Netherlands Antilles
🇮🇹:
  国旗: 🇮🇹
  英文: IT
  中文: 意大利
  其他:
    - Italy
🇭🇰:
  国旗: 🇭🇰
  英文: HK
  中文: 香港
  其他:
    - Hong Kong
    - HongKong
🇷🇴:
  国旗: 🇷🇴
  英文: RO
  中文: 罗马尼亚
  其他:
    - Romania
🇪🇸:
  国旗: 🇪🇸
  英文: ES
  中文: 西班牙
  其他:
    - Spain
🇦🇷:
  国旗: 🇦🇷
  英文: AR
  中文: 阿根廷
  其他:
    - Argentina
🇯🇵:
  国旗: 🇯🇵
  英文: JP
  中文: 日本
  其他:
    - Japan
🇨🇭:
  国旗: 🇨🇭
  英文: CH
  中文: 瑞士
  其他:
    - Switzerland
🇰🇷:
  国旗: 🇰🇷
  英文: KR
  中文: 韩国
  其他:
    - Korea, Republic of
🇹🇷:
  国旗: 🇹🇷
  英文: TR
  中文: 土耳其
  其他:
    - Turkey
🇸🇪:
  国旗: 🇸🇪
  英文: SE
  中文: 瑞典
  其他:
    - Sweden
🇻🇳:
  国旗: 🇻🇳
  英文: VN
  中文: 越南
  其他:
    - Viet Nam
    - VietNam
🇿🇦:
  国旗: 🇿🇦
  英文: ZA
  中文: 南非
  其他:
    - South Africa
    - SouthAfrica
🇮🇷:
  国旗: 🇮🇷
  英文: IR
  中文: 伊朗
  其他:
    - Iran, Islamic Republic of
🇧🇬:
  国旗: 🇧🇬
  英文: BG
  中文: 保加利亚
  其他:
    - Bulgaria
🇦🇹:
  国旗: 🇦🇹
  英文: AT
  中文: 奥地利
  其他:
    - Austria
🇳🇿:
  国旗: 🇳🇿
  英文: NZ
  中文: 新西兰
  其他:
    - New Zealand
    - NewZealand
🇲🇽:
  国旗: 🇲🇽
  英文: MX
  中文: 墨西哥
  其他:
    - Mexico
🇨🇿:
  国旗: 🇨🇿
  英文: CZ
  中文: 捷克
  其他:
    - Czech Republic
    - CzechRepublic
🇸🇬:
  国旗: 🇸🇬
  英文: SG
  中文: 新加坡
  其他:
    - Singapore
🇵🇭:
  国旗: 🇵🇭
  英文: PH
  中文: 菲律宾
  其他:
    - Philippines
🇹🇭:
  国旗: 🇹🇭
  英文: TH
  中文: 泰国
  其他:
    - Thailand
🇨🇴:
  国旗: 🇨🇴
  英文: CO
  中文: 哥伦比亚
  其他:
    - Colombia
🇩🇰:
  国旗: 🇩🇰
  英文: DK
  中文: 丹麦
  其他:
    - Denmark
🇹🇼:
  国旗: 🇹🇼
  英文: TW
  中文: 台湾
  其他:
    - Taiwan
    - Tai wan
🇳🇴:
  国旗: 🇳🇴
  英文: NO
  中文: 挪威
  其他:
    - Norway
🇧🇪:
  国旗: 🇧🇪
  英文: BE
  中文: 比利时
  其他:
    - Belgium
🇨🇱:
  国旗: 🇨🇱
  英文: CL
  中文: 智利
  其他:
    - Chile
🇫🇮:
  国旗: 🇫🇮
  英文: FI
  中文: 芬兰
  其他:
    - Finland
🇵🇰:
  国旗: 🇵🇰
  英文: PK
  中文: 巴基斯坦
  其他:
    - Pakistan
🇮🇱:
  国旗: 🇮🇱
  英文: IL
  中文: 以色列
  其他:
    - Israel
🇲🇾:
  国旗: 🇲🇾
  英文: MY
  中文: 马来西亚
  其他:
    - Malaysia
🇪🇺:
  国旗: 🇪🇺
  英文: EU
  中文: 欧洲联盟
  其他:
    - European Union
    - EuropeanUnion
🇱🇻:
  国旗: 🇱🇻
  英文: LV
  中文: 拉脱维亚
  其他:
    - Latvia
🇭🇺:
  国旗: 🇭🇺
  英文: HU
  中文: 匈牙利
  其他:
    - Hungary
🇮🇪:
  国旗: 🇮🇪
  英文: IE
  中文: 爱尔兰
  其他:
    - Ireland
🇳🇬:
  国旗: 🇳🇬
  英文: NG
  中文: 尼日利亚
  其他:
    - Nigeria
🇸🇮:
  国旗: 🇸🇮
  英文: SI
  中文: 斯洛文尼亚
  其他:
    - Slovenia
🇬🇷:
  国旗: 🇬🇷
  英文: GR
  中文: 希腊
  其他:
    - Greece
🇪🇨:
  国旗: 🇪🇨
  英文: EC
  中文: 厄瓜多尔
  其他:
    - Ecuador
🇰🇪:
  国旗: 🇰🇪
  英文: KE
  中文: 肯尼亚
  其他:
    - Kenya
🇻🇪:
  国旗: 🇻🇪
  英文: VE
  中文: 委内瑞拉
  其他:
    - Venezuela, Bolivarian Republic of
🇸🇰:
  国旗: 🇸🇰
  英文: SK
  中文: 斯洛伐克
  其他:
    - Slovakia
🇱🇹:
  国旗: 🇱🇹
  英文: LT
  中文: 立陶宛
  其他:
    - Lithuania
🇪🇪:
  国旗: 🇪🇪
  英文: EE
  中文: 爱沙尼亚
  其他:
    - Estonia
🇮🇶:
  国旗: 🇮🇶
  英文: IQ
  中文: 伊拉克
  其他:
    - Iraq
🇲🇩:
  国旗: 🇲🇩
  英文: MD
  中文: 摩尔多瓦
  其他:
    - Moldova, Republic of
🇵🇪:
  国旗: 🇵🇪
  英文: PE
  中文: 秘鲁
  其他:
    - Peru
🇰🇿:
  国旗: 🇰🇿
  英文: KZ
  中文: 哈萨克斯坦
  其他:
    - Kazakhstan
🇷🇸:
  国旗: 🇷🇸
  英文: RS
  中文: 塞尔维亚
  其他:
    - Serbia
🇸🇦:
  国旗: 🇸🇦
  英文: SA
  中文: 沙特阿拉伯
  其他:
    - Saudi Arabia
    - SaudiArabia
🇳🇵:
  国旗: 🇳🇵
  英文: NP
  中文: 尼泊尔
  其他:
    - Nepal
🇭🇷:
  国旗: 🇭🇷
  英文: HR
  中文: 克罗地亚
  其他:
    - Croatia
🇩🇴:
  国旗: 🇩🇴
  英文: DO
  中文: 多米尼加共和国
  其他:
    - Dominican Republic
    - DominicanRepublic
🇱🇧:
  国旗: 🇱🇧
  英文: LB
  中文: 黎巴嫩
  其他:
    - Lebanon
🇨🇾:
  国旗: 🇨🇾
  英文: CY
  中文: 塞浦路斯
  其他:
    - Cyprus
🇵🇹:
  国旗: 🇵🇹
  英文: PT
  中文: 葡萄牙
  其他:
    - Portugal
🇦🇪:
  国旗: 🇦🇪
  英文: AE
  中文: 阿联酋
  其他:
    - United Arab Emirates
🇵🇦:
  国旗: 🇵🇦
  英文: PA
  中文: 巴拿马
  其他:
    - Panama
🇲🇲:
  国旗: 🇲🇲
  英文: MM
  中文: 缅甸
  其他:
    - Myanmar
🇬🇪:
  国旗: 🇬🇪
  英文: GE
  中文: 格鲁吉亚
  其他:
    - Georgia
🇰🇭:
  国旗: 🇰🇭
  英文: KH
  中文: 柬埔寨
  其他:
    - Cambodia
🇧🇾:
  国旗: 🇧🇾
  英文: BY
  中文: 白俄罗斯
  其他:
    - Belarus
🇱🇺:
  国旗: 🇱🇺
  英文: LU
  中文: 卢森堡
  其他:
    - Luxembourg
🇦🇲:
  国旗: 🇦🇲
  英文: AM
  中文: 亚美尼亚
  其他:
    - Armenia
🇬🇭:
  国旗: 🇬🇭
  英文: GH
  中文: 加纳
  其他:
    - Ghana
🇦🇱:
  国旗: 🇦🇱
  英文: AL
  中文: 阿尔巴尼亚
  其他:
    - Albania
🇹🇿:
  国旗: 🇹🇿
  英文: TZ
  中文: 坦桑尼亚
  其他:
    - Tanzania, United Republic of
🇨🇷:
  国旗: 🇨🇷
  英文: CR
  中文: 哥斯达黎加
  其他:
    - Costa Rica
    - CostaRica
🇭🇳:
  国旗: 🇭🇳
  英文: HN
  中文: 洪都拉斯
  其他:
    - Honduras
🇺🇿:
  国旗: 🇺🇿
  英文: UZ
  中文: 乌兹别克斯坦
  其他:
    - Uzbekistan
🇵🇷:
  国旗: 🇵🇷
  英文: PR
  中文: 波多黎各
  其他:
    - Puerto Rico
    - Puerto Rico
🇪🇬:
  国旗: 🇪🇬
  英文: EG
  中文: 埃及
  其他:
    - Egypt
🇵🇾:
  国旗: 🇵🇾
  英文: PY
  中文: 巴拉圭
  其他:
    - Paraguay
🇸🇨:
  国旗: 🇸🇨
  英文: SC
  中文: 塞舌尔
  其他:
    - Seychelles
🇮🇸:
  国旗: 🇮🇸
  英文: IS
  中文: 冰岛
  其他:
    - Iceland
🇦🇿:
  国旗: 🇦🇿
  英文: AZ
  中文: 阿塞拜疆
  其他:
    - Azerbaijan
🇬🇹:
  国旗: 🇬🇹
  英文: GT
  中文: 危地马拉
  其他:
    - Guatemala
🇰🇼:
  国旗: 🇰🇼
  英文: KW
  中文: 科威特
  其他:
    - Kuwait
🇦🇴:
  国旗: 🇦🇴
  英文: AO
  中文: 安哥拉
  其他:
    - Angola
🇦🇫:
  国旗: 🇦🇫
  英文: AF
  中文: 阿富汗
  其他:
    - Afghanistan
🇲🇳:
  国旗: 🇲🇳
  英文: MN
  中文: 蒙古
  其他:
    - Mongolia
🇵🇸:
  国旗: 🇵🇸
  英文: PS
  中文: 巴勒斯坦
  其他:
    - Palestine
🇺🇬:
  国旗: 🇺🇬
  英文: UG
  中文: 乌干达
  其他:
    - Uganda
🇰🇬:
  国旗: 🇰🇬
  英文: KG
  中文: 吉尔吉斯斯坦
  其他:
    - Kyrgyzstan
🇧🇴:
  国旗: 🇧🇴
  英文: BO
  中文: 玻利维亚
  其他:
    - Bolivia
🇲🇰:
  国旗: 🇲🇰
  英文: MK
  中文: 北马其顿
  其他:
    - Macedonia
🇲🇺:
  国旗: 🇲🇺
  英文: MU
  中文: 毛里求斯
  其他:
    - Mauritius
🇲🇹:
  国旗: 🇲🇹
  英文: MT
  中文: 马耳他
  其他:
    - Malta
🇨🇩:
  国旗: 🇨🇩
  英文: CD
  中文: 刚果民主共和国
  其他:
    - Congo
🇧🇦:
  国旗: 🇧🇦
  英文: BA
  中文: 波斯尼亚和黑塞哥维那
  其他:
    - Bosnia and Herzegovina
🇸🇻:
  国旗: 🇸🇻
  英文: SV
  中文: 萨尔瓦多
  其他:
    - El Salvador
🇯🇴:
  国旗: 🇯🇴
  英文: JO
  中文: 约旦
  其他:
    - Jordan
🇻🇬:
  国旗: 🇻🇬
  英文: VG
  中文: 英属维尔京群岛
  其他:
    - Virgin Islands, British
🇺🇾:
  国旗: 🇺🇾
  英文: UY
  中文: 乌拉圭
  其他:
    - Uruguay
🇵🇬:
  国旗: 🇵🇬
  英文: PG
  中文: 巴布亚新几内亚
  其他:
    - Papua New Guinea
🇱🇦:
  国旗: 🇱🇦
  英文: LA
  中文: 老挝
  其他:
    - Lao Peoples Democratic Republic
🇧🇿:
  国旗: 🇧🇿
  英文: BZ
  中文: 伯利兹
  其他:
    - Belize
🇿🇼:
  国旗: 🇿🇼
  英文: ZW
  中文: 津巴布韦
  其他:
    - Zimbabwe
🇲🇿:
  国旗: 🇲🇿
  英文: MZ
  中文: 莫桑比克
  其他:
    - Mozambique
🇨🇼:
  国旗: 🇨🇼
  英文: CW
  中文: 库拉索
  其他:
    - Curaçao
🇨🇲:
  国旗: 🇨🇲
  英文: CM
  中文: 喀麦隆
  其他:
    - Cameroon
🇲🇼:
  国旗: 🇲🇼
  英文: MW
  中文: 马拉维
  其他:
    - Malawi
🇧🇼:
  国旗: 🇧🇼
  英文: BW
  中文: 博茨瓦纳
  其他:
    - Botswana
🇷🇼:
  国旗: 🇷🇼
  英文: RW
  中文: 卢旺达
  其他:
    - Rwanda
🇳🇮:
  国旗: 🇳🇮
  英文: NI
  中文: 尼加拉瓜
  其他:
    - Nicaragua
🇧🇹:
  国旗: 🇧🇹
  英文: BT
  中文: 不丹
  其他:
    - Bhutan
🇹🇯:
  国旗: 🇹🇯
  英文: TJ
  中文: 塔吉克斯坦
  其他:
    - Tajikistan
🇱🇾:
  国旗: 🇱🇾
  英文: LY
  中文: 利比亚
  其他:
    - Libya
🇬🇮:
  国旗: 🇬🇮
  英文: GI
  中文: 直布罗陀
  其他:
    - Gibraltar
🇧🇫:
  国旗: 🇧🇫
  英文: BF
  中文: 布基纳法索
  其他:
    - Burkina Faso
    - BurkinaFaso
🇲🇦:
  国旗: 🇲🇦
  英文: MA
  中文: 摩洛哥
  其他:
    - Morocco
🇱🇰:
  国旗: 🇱🇰
  英文: LK
  中文: 斯里兰卡
  其他:
    - Sri Lanka
🇿🇲:
  国旗: 🇿🇲
  英文: ZM
  中文: 赞比亚
  其他:
    - Zambia
🇹🇳:
  国旗: 🇹🇳
  英文: TN
  中文: 突尼斯
  其他:
    - Tunisia
🇨🇮:
  国旗: 🇨🇮
  英文: CI
  中文: 科特迪瓦
  其他:
    - Côte dIvoire
    - CôtedIvoire
🇲🇪:
  国旗: 🇲🇪
  英文: ME
  中文: 黑山
  其他:
    - Montenegro
🇧🇭:
  国旗: 🇧🇭
  英文: BH
  中文: 巴林
  其他:
    - Bahrain
🇱🇮:
  国旗: 🇱🇮
  英文: LI
  中文: 列支敦士登
  其他:
    - Liechtenstein
🇸🇸:
  国旗: 🇸🇸
  英文: SS
  中文: 南苏丹
  其他:
    - South Sudan
    - SouthSudan
🇮🇲:
  国旗: 🇮🇲
  英文: IM
  中文: 曼岛
  其他:
    - Isle of Man
🇸🇱:
  国旗: 🇸🇱
  英文: SL
  中文: 塞拉利昂
  其他:
    - Sierra Leone
    - SierraLeone
🇶🇦:
  国旗: 🇶🇦
  英文: QA
  中文: 卡塔尔
  其他:
    - Qatar
🇸🇴:
  国旗: 🇸🇴
  英文: SO
  中文: 索马里
  其他:
    - Somalia
🇧🇲:
  国旗: 🇧🇲
  英文: BM
  中文: 百慕大
  其他:
    - Bermuda
🇧🇯:
  国旗: 🇧🇯
  英文: BJ
  中文: 贝宁
  其他:
    - Benin
🇴🇲:
  国旗: 🇴🇲
  英文: OM
  中文: 阿曼
  其他:
    - Oman
🇬🇳:
  国旗: 🇬🇳
  英文: GN
  中文: 几内亚
  其他:
    - Guinea
🇩🇿:
  国旗: 🇩🇿
  英文: DZ
  中文: 阿尔及利亚
  其他:
    - Algeria
🇨🇬:
  国旗: 🇨🇬
  英文: CG
  中文: 刚果
  其他:
    - Congo
🇹🇩:
  国旗: 🇹🇩
  英文: TD
  中文: 乍得
  其他:
    - Chad
🇸🇳:
  国旗: 🇸🇳
  英文: SN
  中文: 塞内加尔
  其他:
    - Senegal
🇳🇨:
  国旗: 🇳🇨
  英文: NC
  中文: 新喀里多尼亚
  其他:
    - New Caledonia
    - NewCaledonia
🇳🇦:
  国旗: 🇳🇦
  英文: NA
  中文: 纳米比亚
  其他:
    - Namibia
🇬🇦:
  国旗: 🇬🇦
  英文: GA
  中文: 加蓬
  其他:
    - Gabon
🇫🇯:
  国旗: 🇫🇯
  英文: FJ
  中文: 斐济
  其他:
    - Fiji
🇹🇹:
  国旗: 🇹🇹
  英文: TT
  中文: 特立尼达和多巴哥
  其他:
    - Trinidad and Tobago
🇲🇻:
  国旗: 🇲🇻
  英文: MV
  中文: 马尔代夫
  其他:
    - Maldives
🇱🇷:
  国旗: 🇱🇷
  英文: LR
  中文: 利比里亚
  其他:
    - Liberia
🇦🇬:
  国旗: 🇦🇬
  英文: AG
  中文: 安提瓜和巴布达
  其他:
    - Antigua and Barbuda
🇰🇾:
  国旗: 🇰🇾
  英文: KY
  中文: 开曼群岛
  其他:
    - Cayman Islands
    - CaymanIslands
🇸🇿:
  国旗: 🇸🇿
  英文: SZ
  中文: 斯威士兰
  其他:
    - Swaziland
🇲🇴:
  国旗: 🇲🇴
  英文: MO
  中文: 澳门
  其他:
    - Macao
🇭🇹:
  国旗: 🇭🇹
  英文: HT
  中文: 海地
  其他:
    - Haiti
🇧🇸:
  国旗: 🇧🇸
  英文: BS
  中文: 巴哈马
  其他:
    - Bahamas
🇻🇺:
  国旗: 🇻🇺
  英文: VU
  中文: 瓦努阿图
  其他:
    - Vanuatu
🇹🇱:
  国旗: 🇹🇱
  英文: TL
  中文: 东帝汶
  其他:
    - Timor  -Leste
🇸🇩:
  国旗: 🇸🇩
  英文: SD
  中文: 苏丹
  其他:
    - Sudan
🇯🇲:
  国旗: 🇯🇲
  英文: JM
  中文: 牙买加
  其他:
    - Jamaica
🇻🇮:
  国旗: 🇻🇮
  英文: VI
  中文: 美属维尔京群岛
  其他:
    - Virgin Islands, U.S.
🇸🇲:
  国旗: 🇸🇲
  英文: SM
  中文: 圣马力诺
  其他:
    - San Marino
    - SanMarino
🇲🇬:
  国旗: 🇲🇬
  英文: MG
  中文: 马达加斯加
  其他:
    - Madagascar
🇯🇪:
  国旗: 🇯🇪
  英文: JE
  中文: 泽西岛
  其他:
    - Jersey
🇬🇲:
  国旗: 🇬🇲
  英文: GM
  中文: 冈比亚
  其他:
    - Gambia
🇸🇧:
  国旗: 🇸🇧
  英文: SB
  中文: 所罗门群岛
  其他:
    - Solomon Islands
    - SolomonIslands
🇲🇱:
  国旗: 🇲🇱
  英文: ML
  中文: 马里
  其他:
    - Mali
🇧🇮:
  国旗: 🇧🇮
  英文: BI
  中文: 布隆迪
  其他:
    - Burundi
🇼🇸:
  国旗: 🇼🇸
  英文: WS
  中文: 萨摩亚
  其他:
    - Samoa
🇱🇸:
  国旗: 🇱🇸
  英文: LS
  中文: 莱索托
  其他:
    - Lesotho
🇬🇺:
  国旗: 🇬🇺
  英文: GU
  中文: 关岛
  其他:
    - Guam
🇬🇬:
  国旗: 🇬🇬
  英文: GG
  中文: 格恩西岛
  其他:
    - Guernsey
🇬🇩:
  国旗: 🇬🇩
  英文: GD
  中文: 格林纳达
  其他:
    - Grenada
🇨🇻:
  国旗: 🇨🇻
  英文: CV
  中文: 佛得角
  其他:
    - Cape Verde
🇹🇬:
  国旗: 🇹🇬
  英文: TG
  中文: 多哥
  其他:
    - Togo
🇷🇪:
  国旗: 🇷🇪
  英文: RE
  中文: 留尼汪
  其他:
    - RÉUNION
🇳🇪:
  国旗: 🇳🇪
  英文: NE
  中文: 尼日尔
  其他:
    - Niger
🇫🇴:
  国旗: 🇫🇴
  英文: FO
  中文: 法罗群岛
  其他:
    - Faroe Islands
    - FaroeIslands
🇧🇳:
  国旗: 🇧🇳
  英文: BN
  中文: 文莱
  其他:
    - Brunei Darussalam
    - BruneiDarussalam
🇧🇧:
  国旗: 🇧🇧
  英文: BB
  中文: 巴巴多斯
  其他:
    - Barbados
🇲🇷:
  国旗: 🇲🇷
  英文: MR
  中文: 毛里塔尼亚
  其他:
    - Mauritania
🇬🇵:
  国旗: 🇬🇵
  英文: GP
  中文: 瓜德罗普
  其他:
    - Guadeloupe
🇪🇹:
  国旗: 🇪🇹
  英文: ET
  中文: 埃塞俄比亚
  其他:
    - Ethiopia
🇸🇷:
  国旗: 🇸🇷
  英文: SR
  中文: 苏里南
  其他:
    - Suriname
🇱🇨:
  国旗: 🇱🇨
  英文: LC
  中文: 圣卢西亚
  其他:
    - Saint Lucia
    - SaintLucia
🇰🇳:
  国旗: 🇰🇳
  英文: KN
  中文: 圣基茨
  其他:
    - Saint Kitts
    - SaintKitts
🇬🇶:
  国旗: 🇬🇶
  英文: GQ
  中文: 赤道几内亚
  其他:
    - Equatorial Guinea
    - EquatorialGuinea
🇩🇲:
  国旗: 🇩🇲
  英文: DM
  中文: 多米尼克
  其他:
    - Dominica
🇹🇲:
  国旗: 🇹🇲
  英文: TM
  中文: 土库曼斯坦
  其他:
    - Turkmenistan
🇸🇾:
  国旗: 🇸🇾
  英文: SY
  中文: 叙利亚
  其他:
    - Syrian Arab Republic
🇲🇭:
  国旗: 🇲🇭
  英文: MH
  中文: 马绍尔
  其他:
    - Marshall Islands
    - MarshallIslands
🇬🇾:
  国旗: 🇬🇾
  英文: GY
  中文: 圭亚那
  其他:
    - Guyana
🇬🇫:
  国旗: 🇬🇫
  英文: GF
  中文: 法属圭亚那
  其他:
    - French Guiana
    - FrenchGuiana
🇨🇺:
  国旗: 🇨🇺
  英文: CU
  中文: 古巴
  其他:
    - Cuba
🇾🇪:
  国旗: 🇾🇪
  英文: YE
  中文: 也门
  其他:
    - Yemen
🇵🇫:
  国旗: 🇵🇫
  英文: PF
  中文: 法属波利尼西亚
  其他:
    - French Polynesia
    - FrenchPolynesia
🇲🇶:
  国旗: 🇲🇶
  英文: MQ
  中文: 马提尼克
  其他:
    - Martinique
🇲🇫:
  国旗: 🇲🇫
  英文: MF
  中文: 圣马丁
  其他:
    - Saint Martin
    - SaintMartin
🇫🇲:
  国旗: 🇫🇲
  英文: FM
  中文: 密克罗尼西亚
  其他:
    - Micronesia
🇩🇯:
  国旗: 🇩🇯
  英文: DJ
  中文: 吉布提
  其他:
    - Djibouti
🇧🇶:
  国旗: 🇧🇶
  英文: BQ
  中文: 博内尔
  其他:
    - Bonaire
🇹🇴:
  国旗: 🇹🇴
  英文: TO
  中文: 汤加
  其他:
    - Tonga
🇵🇼:
  国旗: 🇵🇼
  英文: PW
  中文: 帕劳
  其他:
    - Palau
🇳🇷:
  国旗: 🇳🇷
  英文: NR
  中文: 瑙鲁
  其他:
    - Nauru
🇦🇼:
  国旗: 🇦🇼
  英文: AW
  中文: 阿鲁巴
  其他:
    - Aruba
🇦🇮:
  国旗: 🇦🇮
  英文: AI
  中文: 安圭拉
  其他:
    - Anguilla
🇻🇨:
  国旗: 🇻🇨
  英文: VC
  中文: 圣文森特
  其他:
    - Saint Vincent
    - SaintVincent
🇸🇽:
  国旗: 🇸🇽
  英文: SX
  中文: 圣马丁
  其他:
    - Sint Maarten
    - SintMaarten
🇰🇮:
  国旗: 🇰🇮
  英文: KI
  中文: 基里巴斯
  其他:
    - Kiribati
🇨🇫:
  国旗: 🇨🇫
  英文: CF
  中文: 中非
  其他:
    - Central African Republic
🇧🇱:
  国旗: 🇧🇱
  英文: BL
  中文: 圣巴泰勒米
  其他:
    - Saint Barth
    - SaintBarth
🇻🇦:
  国旗: 🇻🇦
  英文: VA
  中文: 梵蒂冈
  其他:
    - Vatican
🇹🇻:
  国旗: 🇹🇻
  英文: TV
  中文: 图瓦卢
  其他:
    - Tuvalu
🇹🇰:
  国旗: 🇹🇰
  英文: TK
  中文: 托克劳
  其他:
    - Tokelau
🇲🇨:
  国旗: 🇲🇨
  英文: MC
  中文: 摩纳哥
  其他:
    - Monaco
🇦🇸:
  国旗: 🇦🇸
  英文: AS
  中文: 美属萨摩亚
  其他:
    - American Samoa
    - AmericanSamoa
🇦🇩:
  国旗: 🇦🇩
  英文: AD
  中文: 安道尔
  其他:
    - Andorra
🇹🇨:
  国旗: 🇹🇨
  英文: TC
  中文: 特克斯
  其他:
    - Turks and Caicos
🇸🇹:
  国旗: 🇸🇹
  英文: ST
  中文: 圣多美
  其他:
    - Sao Tome
    - SaoTome
🇳🇫:
  国旗: 🇳🇫
  英文: NF
  中文: 诺福克
  其他:
    - Norfolk Island
    - NorfolkIsland
🇲🇵:
  国旗: 🇲🇵
  英文: MP
  中文: 北马里亚纳
  其他:
    - Northern Mariana Islands
🇰🇲:
  国旗: 🇰🇲
  英文: KM
  中文: 科摩罗
  其他:
    - Comoros
🇬🇼:
  国旗: 🇬🇼
  英文: GW
  中文: 几内亚比绍
  其他:
    - Guinea-Bissau
🇫🇰:
  国旗: 🇫🇰
  英文: FK
  中文: 福克兰
  其他:
    - Falkland
🇨🇰:
  国旗: 🇨🇰
  英文: CK
  中文: 库克
  其他:
    - Cook Islands
    - CookIslands
🇾🇹:
  国旗: 🇾🇹
  英文: YT
  中文: 马约特
  其他:
    - Mayotte
🇼🇫:
  国旗: 🇼🇫
  英文: WF
  中文: 瓦利斯
  其他:
    - Wallis
🇵🇲:
  国旗: 🇵🇲
  英文: PM
  中文: 圣皮埃尔
  其他:
    - Saint Pierre
    - SaintPierre
🇳🇺:
  国旗: 🇳🇺
  英文: NU
  中文: 纽埃
  其他:
    - Niue
🇲🇸:
  国旗: 🇲🇸
  英文: MS
  中文: 蒙特塞拉特
  其他:
    - Montserrat
🇰🇵:
  国旗: 🇰🇵
  英文: KP
  中文: 朝鲜
  其他:
    - North Korea
    - NorthKorea
🇮🇴:
  国旗: 🇮🇴
  英文: IO
  中文: 印度洋
  其他:
    - British Indian Ocean
🇬🇱:
  国旗: 🇬🇱
  英文: GL
  中文: 格陵兰
  其他:
    - Greenland
🇪🇷:
  国旗: 🇪🇷
  英文: ER
  中文: 厄立特里亚
  其他:
    - Eritrea
🇦🇽:
  国旗: 🇦🇽
  英文: AX
  中文: 奥兰
  其他:
    - Åland
